policies:
 - name: azure-ingress-admin-ports-allowed
   resource: azure.networksecuritygroup
   filters:
     - type: ingress
       ports: '22'
       access: 'Allow'
       source: '0.0.0.0/0'
     - type: ingress
       ports: '3389'
       access: 'Allow'
       source: '0.0.0.0/0'

